### ISSUE TITLE
Add brand logos

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/alerts.home-assistant.io#118]
Home Assistant has [brand logos](https://github.com/home-assistant/brands) now, and this alerts site seems like another place they could maybe be implemented, for both eye candy and quick scannability. 

Quick mockup of how it could look (these are right aligned only cause I was too lazy to move everything in Photoshop 😆):

![brands](https://i.imgur.com/tF1X3Qw.jpg)

These would use the smaller "icon" variant - `https://brands.home-assistant.io/[integration_name]/icon.png`.

**Comment by balloob** [comment]
There can be multiple integrations linked to a single alert though

**Comment by ludeeus** [comment]
Implemented in #119?
