### ISSUE TITLE
Please add RSS feed to https://alerts.home-assistant.io

### ISSUE THREAD

**Issue by raoulteeuwen** [home-assistant/alerts.home-assistant.io#13]
i tried to add https://alerts.home-assistant.io to my RSS reader, but it can't find a feed. Is adding a feed possible (and would that serve enough people to justify the effort)?

(Issue created based on https://twitter.com/balloob/status/1167109872501981184 )

**Comment by oopsitsaflame** [comment]
I would use it

**Comment by KaiboshOz** [comment]
An RSS feed seems like an ideal compliment to the alerts page - I'd definitely use it if it were implemented.

**Comment by PedroLamas** [comment]
I was about to suggest this, glad someone had done it before and it is already implemented!

My usage scenario is to integrate with IFTTT, so I can just get a notification every time a new alert is posted!
