### ISSUE TITLE
RSS feed broken?

### ISSUE THREAD

**Issue by metbril** [home-assistant/alerts.home-assistant.io#184]
I think the RSS feed is broken. I added a new alert that doesn't show up at Feedly.com. The alert is visible in the feed page however. Perhaps the file structure is incorrect?

https://alerts.home-assistant.io/feed.xml

**Comment by balloob** [comment]
I think that you hit a cached feed. Feedly shows it correct now:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/1444314/90766470-dd869c80-e2eb-11ea-8223-11c878144cfb.png">
