### ISSUE TITLE
Notify the users about breaking changes that the *device manufactures* made

### ISSUE THREAD

**Issue by TheLastGimbus** [home-assistant/alerts.home-assistant.io#239]
Hi there!

I've recently read a [Reddit post](https://www.reddit.com/r/homeassistant/comments/k00ait/psa_tplink_have_updated_some_of_their_smart_plugs/) that my TP-Link Kasa smart plug will get an update that will completley break it's integration with Home Assistant. I was lucky enough to quickly disable it's access to internet, and still have it working but this remineded me of very important issue: **Companies and manufacturers also often break our devices and setups by OTA updates or killing their services**

Therefore, it would be really nice if (with this new service that you're building here) I could subscribe to alerts about different third party services and products that will change/break - not only Home Assistant

**Comment by ludeeus** [comment]
Alerts can be opened against any integration, so yeah.
