### ISSUE TITLE
Change date fields in feed when a post is updated 

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/alerts.home-assistant.io#274]
I created a [blueprint](https://community.home-assistant.io/t/get-notified-any-time-there-is-a-new-home-assistant-alert/256924) to notify people when there's a new alert posted to the [alerts.home-assistant.io feed](https://alerts.home-assistant.io/feed.xml). But I noticed I never got the alert for [Security Disclosure 2](https://alerts.home-assistant.io/#security_disclosure_2.markdown). 

I dug in and realized its because the first Security Disclosure post was updated instead of a new one being posted. Also even though the post was updated the `updated` fields weren't changed. There's two fields that are now inaccurate, the feed itself has an `updated` field and the Security Disclosure 2 entry also has an `updated` field which are both wrong. They both say `2021-01-14T12:00:00.000Z` even though the feed was updated today with a new Security Disclosure.

Can I request that in the future you avoid updating posts and instead post new ones to make it easier for feedreaders like HA's [feedreader](https://www.home-assistant.io/integrations/feedreader/) integration to follow? You can replace alerts if you want just give the update a new publish date so readers can recognize the update. Or at the very least please change the `updated` fields on an update so watchers can pick that up.

**Comment by jazzyisj** [comment]
I think having both created and updated fields would cover all bases.

**Comment by ludeeus** [comment]
`updated` can be added to the md files, that will be used in the feed if present, with a fallback to the created.
https://github.com/home-assistant/alerts.home-assistant.io/blob/66f0c65574dbb846fe7f7dd96f79635105a8e876/computed/feed_xml.liquid#L27
