### ISSUE TITLE
Entries in the alerts RSS feed do not comply with RFC 2.0 specification

### ISSUE THREAD

**Issue by ogajduse** [home-assistant/alerts.home-assistant.io#628]
## Problem Statement
Entries of the RSS feed published at https://alerts.home-assistant.io/feed.xml do not contain `pubDate` field to indicate when the item was published. Each entry contains a `published` field that is not specified in the RSS 2.0 specification. The value of this field does not comply with RFC 822, which is the standard for RSS entries publish time.
For more info on `pubDate` and RFC 822, please see https://www.rssboard.org/rss-specification#hrelementsOfLtitemgt

Current contents of the feed:
```xml
<entry>
<title>
Ambiclimate integration will stop working April 1, 2024
</title>
<link rel="alternate" href="https://alerts.home-assistant.io/alerts/ambiclimate/"/>
<updated>2024-02-01T00:00:01Z</updated>
<published>2024-02-01T00:00:01Z</published>
<id>
https://alerts.home-assistant.io/alerts/ambiclimate/
</id>
<content xml:lang="en" type="html" lang="en">
<h2>Summary</h2>
<p>
All Ambi Climate services will be terminated, effective March 31, 2024, as Ambi Labs winds down business operations. You will be able to continue to use the Ambi Climate service until the end of March 2024.
</p>
<p>
From April 1, 2024, Ambi Climate devices will no longer be able to connect to the Ambi Climate servers, and you will no longer be able to sign into your account.
</p>
<p>
As Ambiclimate devices require a connection to the manufacturers cloud server, they will cease to function from April 1 2024 onwards. We recommend removing the integration from your Home Assistant installation once this happens.
</p>
<p>
Ambiclimate is allowing customers to export their private data, as well as offering a voluntary compensation policy for some customers. View the Ambiclimate website for more details.
</p>
</content>
</entry>
```

## Proposed Solution
Change the `published` tag to `pubDate` as per standard and make its value compliant with RFC 822.

## Context
This issue was created based on observations in https://github.com/custom-components/feedparser/issues/127.

**Comment by ludeeus** [comment]
That feed is using the atom spec, not RSS 2.0
<https://validator.w3.org/feed/docs/atom.html>
For what it is, the fields are correct.

If you would like to see an additional file that follows the RSS 2.0 spec, please raise a feature request for that on the community forums.
https://community.home-assistant.io/c/feature-requests/13

**Comment by ogajduse** [comment]
@ludeeus Thank you for pointing out the Atom spec. TIL that it exists. I should have known that long before.
If I find time, I can try to implement the feed according to RSS 2.0 spec myself.
