### ISSUE TITLE
Ring Video Doorbell Stopped working after ring security breach

### ISSUE THREAD

**Issue by pgrossouw** [home-assistant/alerts.home-assistant.io#64]
The Ring Doorbell seemed to have stopped working, after Ring recently had a security breach on their Video doorbells. 

Amazon seemed to have changed something in the API that now refuses a connection from the Ring Component in HASS. 

Either this component needs to be updated, to support the new Authentication requirements against the Ring API, or support needs to be pulled for this component from HASS.

**Comment by frenck** [comment]
Hi there,

If you are experiencing an issue with the Ring integration, please be sure you are using the latest Home Assistant version.

If it persists to be an issue, please take a look at (or file an issue at) the Home Assistant GitHub issue tracker: https://github.com/home-assistant/home-assistant.

Thanks! 👍

**Comment by pgrossouw** [comment]
Hi Frenck. Latest HASS version has nothing to do with the issue. 

It is a KNOWN issue, and the issue relates to changes made on the Ring API, updating to the latest version of HASS does nothing to resolve the issue. 
See threads here: https://github.com/home-assistant/home-assistant/issues/30076 
and here: https://github.com/home-assistant/home-assistant/issues/25088
and here: https://community.home-assistant.io/t/ring-integration-setup-fails/156240

I Know its the easiest thing in the world to just say "please make sure you are using the latest....bla bla bla", but there is actually an issue, not fixed, experienced by many. So rather see if you can update the API to support the new Auth Methods with Ring.com, publish this in an HA update, and then ask me to update my hass version... I am on the latest.
